import dotenv from 'dotenv';
dotenv.config();

const RESEND_API_KEY = process.env.RESEND_API_KEY;

/**
 * Sends an emergency email notification to the shipment operator.
 * 
 * @param {Object} alert The alert object containing risk details
 * @param {Object} shipment The shipment object
 */
export const sendEmergencyEmail = async (alert, shipment) => {
  if (!RESEND_API_KEY || RESEND_API_KEY === 'your_resend_key_here') {
    console.log('📝 [SIMULATED EMAIL] To: operator@routeguard.ai');
    console.log(`📝 Subject: CRITICAL RISK DETECTED - ${shipment.id}`);
    return { success: true, mocked: true };
  }

  const emailBody = `
    <h1>⚠️ EMERGENCY RISK ALERT: ${shipment.id}</h1>
    <p>The RouteGuard Intelligence Engine has detected a critical risk for <strong>${shipment.name}</strong>.</p>
    <hr />
    <p><strong>Current Risk Score:</strong> ${alert.score}/100</p>
    <p><strong>Root Cause:</strong> ${alert.title}</p>
    <p><strong>AI Recommended Action:</strong> ${alert.message}</p>
    <hr />
    <p><em>This is an automated message generated by RouteGuard (Gemini 2.5 Logic). Please review the Map Dashboard immediately.</em></p>
  `;

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: 'RouteGuard <onboarding@resend.dev>', // Resend trial sender
        to: ['delivered@resend.dev'], // For demo purposes, we send to Resend's test address or your verified one
        subject: `⚠️ ACTION REQUIRED: Critical Risk on ${shipment.id}`,
        html: emailBody,
      }),
    });

    const data = await response.json();
    if (response.ok) {
        console.log(`📧 Official Email Alert sent via Resend for ${shipment.id} (ID: ${data.id})`);
        return { success: true, id: data.id };
    } else {
        console.error('❌ Resend API Error:', data);
        return { success: false, error: data };
    }
  } catch (error) {
    console.error('❌ Email Notification Failed:', error.message);
    return { success: false, error: error.message };
  }
};
